name: Create Repository Archive

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  create-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tar.gz archive (excluding Git and hidden files)
        run: |
          tar -czvf extending-move.tar.gz --exclude='.git' --exclude='.github' --exclude='.*' .

      - name: Upload archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extending-move
          path: extending-move.tar.gz
