name: Upload Repository Artifacts

on:
  # You can customize these triggers based on your needs
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Upload the artifacts
      - name: Upload repository artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extending-move
          path: |
            **
            !.*/
            !.*
          compression-level: 6
          retention-days: 90
